function Gycall(a,psat_obj)

if ~a.n, return, end

dipqv = ifield(a,2);

psat_obj.DAE.Gy = psat_obj.DAE.Gy ...
         - sparse(a.If,a.If,1,psat_obj.DAE.m,psat_obj.DAE.m) ...
         + sparse(a.If,a.p,dipqv(:,1),psat_obj.DAE.m,psat_obj.DAE.m) ...
         + sparse(a.If,a.q,dipqv(:,2),psat_obj.DAE.m,psat_obj.DAE.m) ...
         + sparse(a.If,a.vbus,dipqv(:,3),psat_obj.DAE.m,psat_obj.DAE.m);
