function Gycall(a,psat_obj)

if ~a.n, return, end

k = 0.995*3*sqrt(2)/pi;
c = 3/pi;

Idc = a.u.*psat_obj.DAE.x(a.Idc);
xr = psat_obj.DAE.x(a.xr);
xi = psat_obj.DAE.x(a.xi);

cosa = psat_obj.DAE.y(a.cosa);
cosg = psat_obj.DAE.y(a.cosg);
phir = a.u.*psat_obj.DAE.y(a.phir);
phii = a.u.*psat_obj.DAE.y(a.phii);
Vrdc = ~a.u + psat_obj.DAE.y(a.Vrdc);
Vidc = ~a.u + psat_obj.DAE.y(a.Vidc);
yr = psat_obj.DAE.y(a.yr);
yi = psat_obj.DAE.y(a.yi);

V1 = psat_obj.DAE.y(a.v1);
V2 = psat_obj.DAE.y(a.v2);

mr = a.con(:,11);
mi = a.con(:,12);
Kp = a.con(:,14);

P0 = a.con(:,27);
I0 = a.con(:,26);
uI = a.u.*a.dat(:,9);
uP = a.u.*a.dat(:,10);
uV = a.u.*a.dat(:,11);

za = cosa < a.dat(:,3) & cosa > a.dat(:,4) & a.u; 
zg = cosg < a.dat(:,5) & cosg > a.dat(:,6) & a.u;
zr = yr < a.con(:,21) & yr > a.con(:,22) & a.u; 
zi = yi < a.con(:,23) & yi > a.con(:,24) & a.u;

psat_obj.DAE.Gy = psat_obj.DAE.Gy ...
         + sparse(a.bus1,a.Vrdc,Idc,psat_obj.DAE.m,psat_obj.DAE.m) ...
         - sparse(a.bus2,a.Vidc,Idc,psat_obj.DAE.m,psat_obj.DAE.m) ...
         + sparse(a.v1,a.phir,k*V1.*mr.*Idc.*cos(phir),psat_obj.DAE.m,psat_obj.DAE.m) ...
         + sparse(a.v2,a.phii,k*V2.*mi.*Idc.*cos(phii),psat_obj.DAE.m,psat_obj.DAE.m) ...
         + sparse(a.v1,a.v1,k*mr.*Idc.*sin(phir),psat_obj.DAE.m,psat_obj.DAE.m) ...
         + sparse(a.v2,a.v2,k*mi.*Idc.*sin(phii),psat_obj.DAE.m,psat_obj.DAE.m) ...
         - sparse(a.cosa,a.cosa,1,psat_obj.DAE.m,psat_obj.DAE.m) ...
         + sparse(a.cosa,a.yr,za.*Kp,psat_obj.DAE.m,psat_obj.DAE.m) ...
         - sparse(a.cosa,a.Vrdc,za.*Kp.*uV,psat_obj.DAE.m,psat_obj.DAE.m) ...
         - sparse(a.Vrdc,a.Vrdc,1,psat_obj.DAE.m,psat_obj.DAE.m) ...
         + sparse(a.Vrdc,a.v1,k*cosa.*mr,psat_obj.DAE.m,psat_obj.DAE.m) ...
         + sparse(a.Vrdc,a.cosa,k*za.*V1.*mr,psat_obj.DAE.m,psat_obj.DAE.m) ...
         + sparse(a.phir,a.phir,k*mr.*V1.*sin(phir),psat_obj.DAE.m,psat_obj.DAE.m) ...
         + sparse(a.phir,a.Vrdc,1,psat_obj.DAE.m,psat_obj.DAE.m) ...
         - sparse(a.phir,a.v1,k*mr.*cos(phir),psat_obj.DAE.m,psat_obj.DAE.m) ...
         + sparse(a.phii,a.phii,k*mi.*V2.*sin(phii),psat_obj.DAE.m,psat_obj.DAE.m) ...
         + sparse(a.phii,a.Vidc,1,psat_obj.DAE.m,psat_obj.DAE.m) ...
         - sparse(a.phii,a.v2,k*mi.*cos(phii),psat_obj.DAE.m,psat_obj.DAE.m) ...
         - sparse(a.yr,a.yr,1,psat_obj.DAE.m,psat_obj.DAE.m) ...
         + sparse(a.yr,a.Vrdc,-zr.*uP.*P0./Vrdc./Vrdc,psat_obj.DAE.m,psat_obj.DAE.m) ...
         - sparse(a.cosg,a.cosg,1,psat_obj.DAE.m,psat_obj.DAE.m) ...
         - sparse(a.cosg,a.yi,zg.*Kp,psat_obj.DAE.m,psat_obj.DAE.m) ...
         + sparse(a.cosg,a.Vidc,zg.*Kp.*uV,psat_obj.DAE.m,psat_obj.DAE.m) ...
         - sparse(a.Vidc,a.Vidc,1,psat_obj.DAE.m,psat_obj.DAE.m) ...
         + sparse(a.Vidc,a.v2,k*cosg.*mi,psat_obj.DAE.m,psat_obj.DAE.m) ...
         + sparse(a.Vidc,a.cosg,k*zg.*V2.*mi,psat_obj.DAE.m,psat_obj.DAE.m) ...
         - sparse(a.yi,a.yi,1,psat_obj.DAE.m,psat_obj.DAE.m) ...
         + sparse(a.yi,a.Vidc,-zi.*uP.*P0./Vidc./Vidc,psat_obj.DAE.m,psat_obj.DAE.m);
