function Gycall(a,psat_obj)

if ~a.n, return, end

V1 = psat_obj.DAE.y(a.v1);
V2 = psat_obj.DAE.y(a.v2);
t1 = psat_obj.DAE.y(a.bus1);
t2 = psat_obj.DAE.y(a.bus2);
ss = sin(t1-t2);
cc = cos(t1-t2);

a1 = ss.*a.B;
a2 = cc.*a.B;
a3 = V1.*V2;
a4 = a3.*a1;
a5 = a3.*a2;

t2 = a.con(:,3) == 2;
ta = a.con(:,4) == 1;
Kp = t2.*a.con(:,12);

b1 = ta.*ss.*(a.B + a.y);
b5 = ta.*a3.*cc.*(a.B + a.y);

psat_obj.DAE.Gy = psat_obj.DAE.Gy ...
          + sparse(a.bus1,a.bus1, a5,psat_obj.DAE.m,psat_obj.DAE.m) ...
          + sparse(a.bus1,a.bus2,-a5,psat_obj.DAE.m,psat_obj.DAE.m) ...
          + sparse(a.bus2,a.bus1,-a5,psat_obj.DAE.m,psat_obj.DAE.m) ...
          + sparse(a.bus2,a.bus2, a5,psat_obj.DAE.m,psat_obj.DAE.m);

psat_obj.DAE.Gy = psat_obj.DAE.Gy ...
          + sparse(a.bus2,a.v1,-V2.*a1,psat_obj.DAE.m,psat_obj.DAE.m) ...
          + sparse(a.bus2,a.v2,-V1.*a1,psat_obj.DAE.m,psat_obj.DAE.m) ...
          + sparse(a.bus1,a.v1, V2.*a1,psat_obj.DAE.m,psat_obj.DAE.m) ...
          + sparse(a.bus1,a.v2, V1.*a1,psat_obj.DAE.m,psat_obj.DAE.m);

psat_obj.DAE.Gy = psat_obj.DAE.Gy ...
          + sparse(a.v1,a.bus1, a4,psat_obj.DAE.m,psat_obj.DAE.m) ...
          + sparse(a.v1,a.bus2,-a4,psat_obj.DAE.m,psat_obj.DAE.m) ...
          + sparse(a.v2,a.bus1, a4,psat_obj.DAE.m,psat_obj.DAE.m) ...
          + sparse(a.v2,a.bus2,-a4,psat_obj.DAE.m,psat_obj.DAE.m);

psat_obj.DAE.Gy = psat_obj.DAE.Gy ...
          + sparse(a.v1,a.v1,(2*V1-V2.*cc).*a.B,psat_obj.DAE.m,psat_obj.DAE.m) ...
          + sparse(a.v1,a.v2,-V1.*a2,psat_obj.DAE.m,psat_obj.DAE.m) ...
          + sparse(a.v2,a.v2,(2*V2-V1.*cc).*a.B,psat_obj.DAE.m,psat_obj.DAE.m) ...
          + sparse(a.v2,a.v1,-V2.*a2,psat_obj.DAE.m,psat_obj.DAE.m);

psat_obj.DAE.Gy = psat_obj.DAE.Gy ...
        - sparse(a.x0,a.x0,1,psat_obj.DAE.m,psat_obj.DAE.m) ...
        + sparse(a.x0,a.pref,Kp,psat_obj.DAE.m,psat_obj.DAE.m) ...
        - sparse(a.pref,a.pref,1,psat_obj.DAE.m,psat_obj.DAE.m);

psat_obj.DAE.Gy = psat_obj.DAE.Gy ...
         - sparse(a.x0,a.v1,Kp.*V2.*b1,psat_obj.DAE.m,psat_obj.DAE.m) ...
         - sparse(a.x0,a.v2,Kp.*V1.*b1,psat_obj.DAE.m,psat_obj.DAE.m) ...
         - sparse(a.x0,a.bus1,Kp.*b5,psat_obj.DAE.m,psat_obj.DAE.m) ...
         + sparse(a.x0,a.bus2,Kp.*b5,psat_obj.DAE.m,psat_obj.DAE.m);
