function warn(a,idx,msg,psat_obj)

psat_obj.fm_disp(fm_strjoin('Warning: Synchronous Machine #', ...
               int2str(idx),'(model ',num2str(a.con(idx,5)), ...
               ') at bus ',psat_obj.Bus.names(a.bus(idx)),msg))